# Socceraction

## Import packages and ignore warnings

In [1]:
# Ensure that no .pyc files are generated
import sys

sys.dont_write_bytecode = True

In [2]:
import warnings

import socceraction.spadl as spadl
from socceraction.data.statsbomb import StatsBombLoader

from config import paths, tournaments

In [3]:
# StatsbombLoader.players
warnings.filterwarnings(
    "ignore",
    message="Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version.",
    category=FutureWarning,
)

# spadl.statsbomb.convert_to_actions
warnings.filterwarnings(
    "ignore",
    message="Inferred xy_fidelity_version=2. If this is incorrect, please specify the correct version using the xy_fidelity_version argument",
    category=UserWarning,
)
warnings.filterwarnings(
    "ignore",
    message="A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.",
    category=FutureWarning,
)

## Load Data

In [4]:
# Initialize StatsBomb data loader
SBL = StatsBombLoader(
    getter="local",
    root=str(paths.STATSBOMB_DIR),
)

In [5]:
# Load the list of competitions
competitions_df = SBL.competitions()
competitions_df

,season_id,competition_id,competition_name,country_name,competition_gender,season_name
0,281,9,1. Bundesliga,Germany,male,2023/2024
1,27,9,1. Bundesliga,Germany,male,2015/2016
2,107,1267,African Cup of Nations,Africa,male,2023
3,4,16,Champions League,Europe,male,2018/2019
4,1,16,Champions League,Europe,male,2017/2018
...,...,...,...,...,...,...
70,75,35,UEFA Europa League,Europe,male,1988/1989
71,315,53,UEFA Women's Euro,Europe,female,2025
72,106,53,UEFA Women's Euro,Europe,female,2022
73,107,72,Women's World Cup,International,female,2023
74,30,72,Women's World Cup,International,female,2019

In [6]:
# Define a specific competition and season to work with (e.g., UEFA Euro 2024)
tournament = tournaments.EURO_2024
competition_id = tournament["competition_id"]
season_id = tournament["season_id"]

In [7]:
# Load the games data for the specified competition and season
games_df = SBL.games(
    competition_id=competition_id,
    season_id=season_id,
)

games_df.head()

,game_id,season_id,competition_id,competition_stage,game_day,game_date,home_team_id,away_team_id,home_score,away_score,venue,referee
0,3942819,282,55,Semi-finals,6,2024-07-10 22:00:00,941,768,1,2,Signal-Iduna-Park,Felix Zwayer
1,3943043,282,55,Final,7,2024-07-14 22:00:00,772,768,2,1,Olympiastadion Berlin,François Letexier
2,3942752,282,55,Semi-finals,6,2024-07-09 22:00:00,772,771,2,1,Allianz Arena,Slavko Vinčić
3,3942382,282,55,Quarter-finals,5,2024-07-06 22:00:00,941,909,2,1,Olympiastadion Berlin,Clément Turpin
4,3942349,282,55,Quarter-finals,5,2024-07-05 22:00:00,780,771,0,0,Volksparkstadion,Michael Oliver

In [8]:
# Load the teams data for the specific match
teams_df = SBL.teams(game_id=tournaments.EURO_2024_FINAL_MATCH_ID)
teams_df

   team_id team_name
0      772     Spain
1      768   England

In [9]:
# Load the players data for the specific match
players_df = SBL.players(game_id=tournaments.EURO_2024_FINAL_MATCH_ID)
players_df

,game_id,team_id,player_id,player_name,nickname,jersey_number,is_starter,starting_position_id,starting_position_name,minutes_played
0,3943043,772,3042,Mikel Merino Zazón,Mikel Merino,6,False,0,Substitute,6
1,3943043,772,3477,Álvaro Borja Morata Martín,Álvaro Morata,7,True,23,Center Forward,69
2,3943043,772,4353,Aymeric Laporte,None,14,True,5,Left Center Back,96
3,3943043,772,5202,José Ignacio Fernández Iglesias,Nacho,4,False,0,Substitute,12
4,3943043,772,5721,Daniel Carvajal Ramos,Daniel Carvajal,2,True,2,Right Back,96
5,3943043,772,6655,Fabián Ruiz Peña,Fabián Ruiz,8,True,11,Left Defensive Midfield,96
6,3943043,772,6685,Mikel Oyarzabal Ugarte,Mikel Oyarzabal,21,False,0,Substitute,27
7,3943043,772,6765,Rodrigo Hernández Cascante,Rodri,16,True,9,Right Defensive Midfield,45
8,3943043,772,11748,Unai Simón Mendibil,Unai Simón,23,True,1,Goalkeeper,96
9,3943043,772,16532,Daniel Olmo Carvajal,Daniel Olmo,10,True,19,Center Attacking Midfield,96
10,3943043,772,17620,Marc Cucurella Saseta,Marc Cucurella,24,True,6,Left Back,96
11,3943043,772,22128,Robin Aime Robert Le Normand,Robin Le Normand,3,True,3,Right Center Back,84
12,3943043,772,24921,Martín Zubimendi Ibáñez,Martín Zubimendi,18,False,0,Substitute,51
13,3943043,772,68574,Nicholas Williams Arthuer,Nico Williams,17,True,21,Left Wing,96
14,3943043,772,316046,Lamine Yamal Nasraoui Ebana,Lamine Yamal,19,True,17,Right Wing,90
15,3943043,768,3205,Kyle Walker,None,2,True,2,Right Back,96
16,3943043,768,3244,John Stones,None,5,True,3,Right Center Back,96
17,3943043,768,3382,Luke Shaw,None,3,True,6,Left Back,96
18,3943043,768,3468,Jordan Pickford,None,1,True,1,Goalkeeper,96
19,3943043,768,3834,Ivan Toney,None,17,False,0,Substitute,5
20,3943043,768,3943,Declan Rice,None,4,True,11,Left Defensive Midfield,96
21,3943043,768,4354,Phil Foden,None,11,True,19,Center Attacking Midfield,91
22,3943043,768,4760,Ollie Watkins,None,19,False,0,Substitute,34
23,3943043,768,10955,Harry Kane,None,9,True,23,Center Forward,62
24,3943043,768,22084,Bukayo Saka,None,7,True,17,Right Wing,96
25,3943043,768,30714,Jude Bellingham,None,10,True,21,Left Wing,96
26,3943043,768,34526,Marc Guehi,None,6,True,5,Left Center Back,96
27,3943043,768,39461,Cole Palmer,None,24,False,0,Substitute,25
28,3943043,768,99174,Kobbie Mainoo,None,26,True,9,Right Defensive Midfield,71

In [10]:
# Load the events data for the specific match
events_df = SBL.events(game_id=tournaments.EURO_2024_FINAL_MATCH_ID)
events_df.head()

,game_id,event_id,period_id,team_id,player_id,type_id,type_name,index,timestamp,minute,...,team_name,duration,extra,related_events,player_name,position_id,position_name,location,under_pressure,counterpress
0,3943043,50aa204f-5d65-4145-8597-5d5628fb7898,1,772,NaN,35,Starting XI,1,0 days 00:00:00,0,...,Spain,0.000000,"{'tactics': {'formation': 4231, 'lineup': [{'p...",[],NaN,NaN,NaN,NaN,False,False
1,3943043,a279cbee-9ab3-4cfb-9c51-27cacc1bf2a2,1,768,NaN,35,Starting XI,2,0 days 00:00:00,0,...,England,0.000000,"{'tactics': {'formation': 4231, 'lineup': [{'p...",[],NaN,NaN,NaN,NaN,False,False
2,3943043,d2126e70-9f04-4bb7-ba2b-9377836d1757,1,768,NaN,18,Half Start,3,0 days 00:00:00,0,...,England,0.000000,{},[54d78bfa-4146-42bd-acdc-97bcd393dd81],NaN,NaN,NaN,NaN,False,False
3,3943043,54d78bfa-4146-42bd-acdc-97bcd393dd81,1,772,NaN,18,Half Start,4,0 days 00:00:00,0,...,Spain,0.000000,{},[d2126e70-9f04-4bb7-ba2b-9377836d1757],NaN,NaN,NaN,NaN,False,False
4,3943043,152820f0-6ca9-4df3-943b-a67d568ff472,1,768,99174.0,30,Pass,5,0 days 00:00:00.340000,0,...,England,2.529454,"{'pass': {'recipient': {'id': 3468, 'name': 'J...",[d64668c7-747c-4a7d-912c-e1c3ff357a67],Kobbie Mainoo,9.0,Right Defensive Midfield,"[60.0, 40.0]",False,False

In [11]:
# Load the 360 data for the specific match
events_360_df = SBL.events(game_id=tournaments.EURO_2024_FINAL_MATCH_ID, load_360=True)
events_360_df.head()

,game_id,event_id,period_id,team_id,player_id,type_id,type_name,index,timestamp,minute,...,extra,related_events,player_name,position_id,position_name,location,under_pressure,counterpress,visible_area_360,freeze_frame_360
0,3943043,50aa204f-5d65-4145-8597-5d5628fb7898,1,772,NaN,35,Starting XI,1,0 days 00:00:00,0,...,"{'tactics': {'formation': 4231, 'lineup': [{'p...",[],NaN,NaN,NaN,NaN,False,False,NaN,NaN
1,3943043,a279cbee-9ab3-4cfb-9c51-27cacc1bf2a2,1,768,NaN,35,Starting XI,2,0 days 00:00:00,0,...,"{'tactics': {'formation': 4231, 'lineup': [{'p...",[],NaN,NaN,NaN,NaN,False,False,NaN,NaN
2,3943043,d2126e70-9f04-4bb7-ba2b-9377836d1757,1,768,NaN,18,Half Start,3,0 days 00:00:00,0,...,{},[54d78bfa-4146-42bd-acdc-97bcd393dd81],NaN,NaN,NaN,NaN,False,False,NaN,NaN
3,3943043,54d78bfa-4146-42bd-acdc-97bcd393dd81,1,772,NaN,18,Half Start,4,0 days 00:00:00,0,...,{},[d2126e70-9f04-4bb7-ba2b-9377836d1757],NaN,NaN,NaN,NaN,False,False,NaN,NaN
4,3943043,152820f0-6ca9-4df3-943b-a67d568ff472,1,768,99174.0,30,Pass,5,0 days 00:00:00.340000,0,...,"{'pass': {'recipient': {'id': 3468, 'name': 'J...",[d64668c7-747c-4a7d-912c-e1c3ff357a67],Kobbie Mainoo,9.0,Right Defensive Midfield,"[60.0, 40.0]",False,False,"[76.727979231533, 80.0, 43.48260274825104, 80....","[{'teammate': True, 'actor': False, 'keeper': ..."

## SPADL

In [12]:
# Get the home team ID for the specific match
home_team_id = games_df[games_df["game_id"] == tournaments.EURO_2024_FINAL_MATCH_ID]["home_team_id"].iloc[0]

In [13]:
# Convert the events data of the specific match to SPADL actions
actions_df = spadl.statsbomb.convert_to_actions(events_df, home_team_id=home_team_id)
actions_df

,game_id,original_event_id,period_id,time_seconds,team_id,player_id,start_x,start_y,end_x,end_y,type_id,result_id,bodypart_id,action_id
0,3943043,152820f0-6ca9-4df3-943b-a67d568ff472,1,0.340,768,99174.0,52.54375,33.9575,82.81875,32.9375,0,1,5,0
1,3943043,9c107df3-a3c8-4ad5-bc35-00214087a105,1,2.870,768,3468.0,82.81875,32.9375,79.93125,26.8175,21,1,0,1
2,3943043,237201b8-aef8-4823-b282-e82875795c07,1,4.742,768,3468.0,79.93125,26.8175,0.04375,57.5025,0,0,4,2
3,3943043,238f44cb-0f18-4217-85b5-8cc6345278fe,1,34.440,772,11748.0,5.99375,34.3825,7.91875,19.4225,22,1,4,3
4,3943043,987a3f1e-4dc4-4833-8896-5513e35c3fc5,1,35.658,772,22128.0,7.91875,19.4225,7.74375,19.4225,21,1,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1878,3943043,5d909b16-f11b-4d1c-8657-7eb5421ed102,2,2860.833,768,3468.0,54.73125,30.5575,12.46875,50.1075,3,0,4,1878
1879,3943043,4a610ec1-edf3-4066-bd69-cb2a28f2981c,2,2863.751,772,4353.0,12.46875,50.1075,10.89375,65.9175,18,1,1,1879
1880,3943043,c11721ac-1ddd-4a7d-8ee9-6ba005b6380f,2,2865.814,768,22084.0,10.89375,65.9175,12.73125,66.0025,21,1,0,1880
1881,3943043,8eab51fc-0835-4fdb-8fe2-9c38fc38c46b,2,2867.318,768,22084.0,12.73125,66.0025,12.73125,66.0025,8,0,0,1881
1882,3943043,9be6bb15-7db5-483e-aee7-44430f07c38f,2,2929.145,772,3042.0,86.05625,45.9425,86.05625,45.9425,8,0,0,1882

In [14]:
# Replace IDs with names in the actions DataFrame
actions_df = (
    spadl.add_names(actions_df)
    .merge(SBL.teams(game_id=tournaments.EURO_2024_FINAL_MATCH_ID))
    .merge(SBL.players(game_id=tournaments.EURO_2024_FINAL_MATCH_ID))
)
actions_df

,game_id,original_event_id,period_id,time_seconds,team_id,player_id,start_x,start_y,end_x,end_y,...,result_name,bodypart_name,team_name,player_name,nickname,jersey_number,is_starter,starting_position_id,starting_position_name,minutes_played
0,3943043,152820f0-6ca9-4df3-943b-a67d568ff472,1,0.340,768,99174.0,52.54375,33.9575,82.81875,32.9375,...,success,foot_right,England,Kobbie Mainoo,None,26,True,9,Right Defensive Midfield,71
1,3943043,9c107df3-a3c8-4ad5-bc35-00214087a105,1,2.870,768,3468.0,82.81875,32.9375,79.93125,26.8175,...,success,foot,England,Jordan Pickford,None,1,True,1,Goalkeeper,96
2,3943043,237201b8-aef8-4823-b282-e82875795c07,1,4.742,768,3468.0,79.93125,26.8175,0.04375,57.5025,...,fail,foot_left,England,Jordan Pickford,None,1,True,1,Goalkeeper,96
3,3943043,238f44cb-0f18-4217-85b5-8cc6345278fe,1,34.440,772,11748.0,5.99375,34.3825,7.91875,19.4225,...,success,foot_left,Spain,Unai Simón Mendibil,Unai Simón,23,True,1,Goalkeeper,96
4,3943043,987a3f1e-4dc4-4833-8896-5513e35c3fc5,1,35.658,772,22128.0,7.91875,19.4225,7.74375,19.4225,...,success,foot,Spain,Robin Aime Robert Le Normand,Robin Le Normand,3,True,3,Right Center Back,84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1878,3943043,5d909b16-f11b-4d1c-8657-7eb5421ed102,2,2860.833,768,3468.0,54.73125,30.5575,12.46875,50.1075,...,fail,foot_left,England,Jordan Pickford,None,1,True,1,Goalkeeper,96
1879,3943043,4a610ec1-edf3-4066-bd69-cb2a28f2981c,2,2863.751,772,4353.0,12.46875,50.1075,10.89375,65.9175,...,success,head,Spain,Aymeric Laporte,None,14,True,5,Left Center Back,96
1880,3943043,c11721ac-1ddd-4a7d-8ee9-6ba005b6380f,2,2865.814,768,22084.0,10.89375,65.9175,12.73125,66.0025,...,success,foot,England,Bukayo Saka,None,7,True,17,Right Wing,96
1881,3943043,8eab51fc-0835-4fdb-8fe2-9c38fc38c46b,2,2867.318,768,22084.0,12.73125,66.0025,12.73125,66.0025,...,fail,foot,England,Bukayo Saka,None,7,True,17,Right Wing,96
1882,3943043,9be6bb15-7db5-483e-aee7-44430f07c38f,2,2929.145,772,3042.0,86.05625,45.9425,86.05625,45.9425,...,fail,foot,Spain,Mikel Merino Zazón,Mikel Merino,6,False,0,Substitute,6

## Number of matches

In [15]:
n_matches_list = []

for _, row in competitions_df.iterrows():
    season_id = row["season_id"]
    competition_id = row["competition_id"]

    # Load the matches for the given competition and season
    matches_df = SBL.games(competition_id=competition_id, season_id=season_id)
    n_matches = len(matches_df)
    n_matches_list.append(n_matches)

competitions_with_games_df = competitions_df.copy()
competitions_with_games_df.insert(4, "n_matches", n_matches_list)

In [16]:
print(competitions_with_games_df.to_string())

    season_id  competition_id         competition_name               country_name  n_matches competition_gender season_name
0         281               9            1. Bundesliga                    Germany         34               male   2023/2024
1          27               9            1. Bundesliga                    Germany        306               male   2015/2016
2         107            1267   African Cup of Nations                     Africa         52               male        2023
3           4              16         Champions League                     Europe          1               male   2018/2019
4           1              16         Champions League                     Europe          1               male   2017/2018
5           2              16         Champions League                     Europe          1               male   2016/2017
6          27              16         Champions League                     Europe          1               male   2015/2016
7          26              16         Champions League                     Europe          1               male   2014/2015
8          25              16         Champions League                     Europe          1               male   2013/2014
9          24              16         Champions League                     Europe          1               male   2012/2013
10         23              16         Champions League                     Europe          1               male   2011/2012
11         22              16         Champions League                     Europe          1               male   2010/2011
12         21              16         Champions League                     Europe          1               male   2009/2010
13         41              16         Champions League                     Europe          1               male   2008/2009
14         39              16         Champions League                     Europe          1               male   2006/2007
15         37              16         Champions League                     Europe          1               male   2004/2005
16         44              16         Champions League                     Europe          1               male   2003/2004
17         76              16         Champions League                     Europe          1               male   1999/2000
18        277              16         Champions League                     Europe          1               male   1972/1973
19         71              16         Champions League                     Europe          1               male   1971/1972
20        276              16         Champions League                     Europe          1               male   1970/1971
21        282             223             Copa America              South America         32               male        2024
22         84              87             Copa del Rey                      Spain          1               male   1983/1984
23        268              87             Copa del Rey                      Spain          1               male   1982/1983
24        279              87             Copa del Rey                      Spain          1               male   1977/1978
25         90              37  FA Women's Super League                    England        131             female   2020/2021
26         42              37  FA Women's Super League                    England         87             female   2019/2020
27          4              37  FA Women's Super League                    England        108             female   2018/2019
28        274            1470       FIFA U20 World Cup              International          1               male        1979
29        106              43           FIFA World Cup              International         64               male        2022
30          3              43           FIFA World Cup              International         64               male        2018
31         55              43           FIFA World Cup              International          1               male        1990
32         54              43           FIFA World Cup              International          3               male        1986
33         51              43           FIFA World Cup              International          6               male        1974
34        272              43           FIFA World Cup              International          6               male        1970
35        270              43           FIFA World Cup              International          1               male        1962
36        269              43           FIFA World Cup              International          2               male        1958
37        108            1238      Indian Super league                      India        115               male   2021/2022
38         90              11                  La Liga                      Spain         35               male   2020/2021
39         42              11                  La Liga                      Spain         33               male   2019/2020
40          4              11                  La Liga                      Spain         34               male   2018/2019
41          1              11                  La Liga                      Spain         36               male   2017/2018
42          2              11                  La Liga                      Spain         34               male   2016/2017
43         27              11                  La Liga                      Spain        380               male   2015/2016
44         26              11                  La Liga                      Spain         38               male   2014/2015
45         25              11                  La Liga                      Spain         31               male   2013/2014
46         24              11                  La Liga                      Spain         32               male   2012/2013
47         23              11                  La Liga                      Spain         37               male   2011/2012
48         22              11                  La Liga                      Spain         33               male   2010/2011
49         21              11                  La Liga                      Spain         35               male   2009/2010
50         41              11                  La Liga                      Spain         31               male   2008/2009
51         40              11                  La Liga                      Spain         28               male   2007/2008
52         39              11                  La Liga                      Spain         26               male   2006/2007
53         38              11                  La Liga                      Spain         17               male   2005/2006
54         37              11                  La Liga                      Spain          7               male   2004/2005
55        278              11                  La Liga                      Spain          1               male   1973/1974
56         48              81         Liga Profesional                  Argentina          1               male   1997/1998
57        275              81         Liga Profesional                  Argentina          1               male        1981
58        235               7                  Ligue 1                     France         32               male   2022/2023
59        108               7                  Ligue 1                     France         26               male   2021/2022
60         27               7                  Ligue 1                     France        377               male   2015/2016
61        107              44      Major League Soccer   United States of America          6               male        2023
62         68             116    North American League  North and Central America          1               male        1977
63          3              49                     NWSL   United States of America         36             female        2018
64         27               2           Premier League                    England        380               male   2015/2016
65         44               2           Premier League                    England         38               male   2003/2004
66         27              12                  Serie A                      Italy        380               male   2015/2016
67         86              12                  Serie A                      Italy          1               male   1986/1987
68        282              55                UEFA Euro                     Europe         51               male        2024
69         43              55                UEFA Euro                     Europe         51               male        2020
70         75              35       UEFA Europa League                     Europe          3               male   1988/1989
71        315              53        UEFA Women's Euro                     Europe         31             female        2025
72        106              53        UEFA Women's Euro                     Europe         31             female        2022
73        107              72        Women's World Cup              International         64             female        2023
74         30              72        Women's World Cup              International         52             female        2019

In [17]:
three_sixty_matches = [int(p.stem) for p in paths.STATSBOMB_THREE_SIXTY_DIR.glob("*.json")]

In [18]:
n_matches_360_list = []

for _, row in competitions_with_games_df.iterrows():
    competition_id = row["competition_id"]
    season_id = row["season_id"]

    matches_df = SBL.games(competition_id=competition_id, season_id=season_id)
    match_ids = matches_df["game_id"].tolist()
    n_matches_360 = sum(1 for match_id in match_ids if match_id in three_sixty_matches)
    n_matches_360_list.append(n_matches_360)

competitions_with_360_games_df = competitions_with_games_df.copy()
competitions_with_360_games_df.insert(5, "n_matches_360", n_matches_360_list)

In [19]:
print(competitions_with_360_games_df.to_string())

    season_id  competition_id         competition_name               country_name  n_matches  n_matches_360 competition_gender season_name
0         281               9            1. Bundesliga                    Germany         34             34               male   2023/2024
1          27               9            1. Bundesliga                    Germany        306              0               male   2015/2016
2         107            1267   African Cup of Nations                     Africa         52              0               male        2023
3           4              16         Champions League                     Europe          1              0               male   2018/2019
4           1              16         Champions League                     Europe          1              0               male   2017/2018
5           2              16         Champions League                     Europe          1              0               male   2016/2017
6          27              16         Champions League                     Europe          1              0               male   2015/2016
7          26              16         Champions League                     Europe          1              0               male   2014/2015
8          25              16         Champions League                     Europe          1              0               male   2013/2014
9          24              16         Champions League                     Europe          1              0               male   2012/2013
10         23              16         Champions League                     Europe          1              0               male   2011/2012
11         22              16         Champions League                     Europe          1              0               male   2010/2011
12         21              16         Champions League                     Europe          1              0               male   2009/2010
13         41              16         Champions League                     Europe          1              0               male   2008/2009
14         39              16         Champions League                     Europe          1              0               male   2006/2007
15         37              16         Champions League                     Europe          1              0               male   2004/2005
16         44              16         Champions League                     Europe          1              0               male   2003/2004
17         76              16         Champions League                     Europe          1              0               male   1999/2000
18        277              16         Champions League                     Europe          1              0               male   1972/1973
19         71              16         Champions League                     Europe          1              0               male   1971/1972
20        276              16         Champions League                     Europe          1              0               male   1970/1971
21        282             223             Copa America              South America         32              0               male        2024
22         84              87             Copa del Rey                      Spain          1              0               male   1983/1984
23        268              87             Copa del Rey                      Spain          1              0               male   1982/1983
24        279              87             Copa del Rey                      Spain          1              0               male   1977/1978
25         90              37  FA Women's Super League                    England        131              0             female   2020/2021
26         42              37  FA Women's Super League                    England         87              0             female   2019/2020
27          4              37  FA Women's Super League                    England        108              0             female   2018/2019
28        274            1470       FIFA U20 World Cup              International          1              0               male        1979
29        106              43           FIFA World Cup              International         64             64               male        2022
30          3              43           FIFA World Cup              International         64              0               male        2018
31         55              43           FIFA World Cup              International          1              0               male        1990
32         54              43           FIFA World Cup              International          3              0               male        1986
33         51              43           FIFA World Cup              International          6              0               male        1974
34        272              43           FIFA World Cup              International          6              0               male        1970
35        270              43           FIFA World Cup              International          1              0               male        1962
36        269              43           FIFA World Cup              International          2              0               male        1958
37        108            1238      Indian Super league                      India        115              0               male   2021/2022
38         90              11                  La Liga                      Spain         35              0               male   2020/2021
39         42              11                  La Liga                      Spain         33              0               male   2019/2020
40          4              11                  La Liga                      Spain         34              0               male   2018/2019
41          1              11                  La Liga                      Spain         36              0               male   2017/2018
42          2              11                  La Liga                      Spain         34              0               male   2016/2017
43         27              11                  La Liga                      Spain        380              0               male   2015/2016
44         26              11                  La Liga                      Spain         38              0               male   2014/2015
45         25              11                  La Liga                      Spain         31              0               male   2013/2014
46         24              11                  La Liga                      Spain         32              0               male   2012/2013
47         23              11                  La Liga                      Spain         37              0               male   2011/2012
48         22              11                  La Liga                      Spain         33              0               male   2010/2011
49         21              11                  La Liga                      Spain         35              0               male   2009/2010
50         41              11                  La Liga                      Spain         31              0               male   2008/2009
51         40              11                  La Liga                      Spain         28              0               male   2007/2008
52         39              11                  La Liga                      Spain         26              0               male   2006/2007
53         38              11                  La Liga                      Spain         17              0               male   2005/2006
54         37              11                  La Liga                      Spain          7              0               male   2004/2005
55        278              11                  La Liga                      Spain          1              0               male   1973/1974
56         48              81         Liga Profesional                  Argentina          1              0               male   1997/1998
57        275              81         Liga Profesional                  Argentina          1              0               male        1981
58        235               7                  Ligue 1                     France         32              0               male   2022/2023
59        108               7                  Ligue 1                     France         26              0               male   2021/2022
60         27               7                  Ligue 1                     France        377              0               male   2015/2016
61        107              44      Major League Soccer   United States of America          6              0               male        2023
62         68             116    North American League  North and Central America          1              0               male        1977
63          3              49                     NWSL   United States of America         36              0             female        2018
64         27               2           Premier League                    England        380              0               male   2015/2016
65         44               2           Premier League                    England         38              0               male   2003/2004
66         27              12                  Serie A                      Italy        380              0               male   2015/2016
67         86              12                  Serie A                      Italy          1              0               male   1986/1987
68        282              55                UEFA Euro                     Europe         51             51               male        2024
69         43              55                UEFA Euro                     Europe         51             51               male        2020
70         75              35       UEFA Europa League                     Europe          3              0               male   1988/1989
71        315              53        UEFA Women's Euro                     Europe         31             31             female        2025
72        106              53        UEFA Women's Euro                     Europe         31             31             female        2022
73        107              72        Women's World Cup              International         64             64             female        2023
74         30              72        Women's World Cup              International         52              0             female        2019